# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr: none

trigger:
    branches:
        exclude:
            - '*'
        include:
            - main

pool:
    name: Hosted VS2017
    demands: npm

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/build/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- script: |
    npm run package-release
  displayName: 'npm extension package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: TfxInstaller@2
  inputs:
    version: 'v0.6.x'

- task: PublishAzureDevOpsExtension@2
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'Azure DevOps Marketplace'
    fileType: 'vsix'
    vsixFile: 'azure-pull-request-hub.vsix'
    updateTasksVersionType: 'patch'
    extensionVersion: '1.$(Build.BuildNumber)'
